export const CLICK_PLAY_AND_BACKWARDS = 'CLICK_PLAY_AND_BACKWARDS';
export const HOVER_PLAY_AND_STOP = 'HOVER_PLAY_AND_STOP';
export const HOVER_PLAY_AND_BACKWARDS = 'HOVER_PLAY_AND_BACKWARDS';
export const CLICK_PLAY = 'CLICK_PLAY';
export const LOOP_PLAY = 'LOOP_PLAY';
export const CLICK_PLAY_AND_SEGMENTS = 'CLICK_PLAY_AND_SEGMENTS';

export const ANIMATION_KEYS = {
  activity: 'activity',
  airplay: 'airplay',
  alertCircle: 'alertCircle',
  alertOctagon: 'alertOctagon',
  alertTriangle: 'alertTriangle',
  archive: 'archive',
  arrowDown: 'arrowDown',
  arrowUp: 'arrowUp',
  bookmark: 'bookmark',
  calendar: 'calendar',
  checkBox: 'checkBox',
  codepen: 'codepen',
  copy: 'copy',
  download: 'download',
  edit: 'edit',
  facebook: 'facebook',
  github: 'github',
  heart: 'heart',
  infinity: 'infinity',
  instagram: 'instagram',
  linkedin: 'linkedin',
  loading: 'loading',
  loading2: 'loading2',
  lock: 'lock',
  mail: 'mail',
  maximizeMinimize: 'maximizeMinimize',
  maximizeMinimize2: 'maximizeMinimize2',
  menu: 'menu',
  menu2: 'menu2',
  menu3: 'menu3',
  menu4: 'menu4',
  microphone: 'microphone',
  microphone2: 'microphone2',
  notification: 'notification',
  notification2: 'notification2',
  playPause: 'playPause',
  playPauseCircle: 'playPauseCircle',
  plusToX: 'plusToX',
  pocket: 'pocket',
  radioButton: 'radioButton',
  scrollDown: 'scrollDown',
  searchToX: 'searchToX',
  settings: 'settings',
  settings2: 'settings2',
  skipBack: 'skipBack',
  skipForward: 'skipForward',
  star: 'star',
  toggle: 'toggle',
  trash: 'trash',
  trash2: 'trash2',
  twitter: 'twitter',
  userMinus: 'userMinus',
  userPlus: 'userPlus',
  userX: 'userX',
  video: 'video',
  video2: 'video2',
  visibility: 'visibility',
  visibility2: 'visibility2',
  volume: 'volume',
  youtube: 'youtube',
  youtubePlay: 'youtubePlay',
};
