export const CLICK_PLAY_AND_BACKWARDS = 'CLICK_PLAY_AND_BACKWARDS';
export const HOVER_PLAY_AND_STOP = 'HOVER_PLAY_AND_STOP';
export const HOVER_PLAY_AND_BACKWARDS = 'HOVER_PLAY_AND_BACKWARDS';
export const CLICK_PLAY = 'CLICK_PLAY';
export const LOOP_PLAY = 'LOOP_PLAY';
export const CLICK_PLAY_AND_SEGMENTS = 'CLICK_PLAY_AND_SEGMENTS';