#!/usr/bin/env node
// Syncs src/lib, src/icons.ts and the README icon list with the useAnimations catalog (icons.json).
//
//   node scripts/sync-icons.mjs [path-or-url-to-icons.json]
//
// Defaults to https://useanimations.com/icons.json. When a local icons.json is given, Lottie files are
// read from the sibling icons/ directory if present, otherwise downloaded from the catalog URLs.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2] ?? 'https://useanimations.com/icons.json';
const isUrl = /^https?:\/\//.test(source);

const readSource = async (location) => {
  if (/^https?:\/\//.test(location)) {
    const res = await fetch(location);
    if (!res.ok) throw new Error(`${location}: HTTP ${res.status}`);
    return res.text();
  }
  return readFileSync(location, 'utf8');
};

const lottieLocation = (url) => {
  if (isUrl) return url;
  const local = join(dirname(source), new URL(url).pathname);
  return existsSync(local) ? local : url;
};

// 'alert-circle' -> 'alertCircle', 'trash-v2' -> 'trash2'
const toKey = (id) =>
  id.replace(/-v(\d+)$/, '$1').replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const catalog = JSON.parse(await readSource(source));
const icons = [];

for (const icon of catalog.icons) {
  const derived = toKey(icon.id);
  const published = icon.react?.import?.match(/lib\/(\w+)'/)?.[1];
  if (published && published !== derived) {
    console.warn(
      `! ${icon.id}: catalog import "${published}" differs from derived key "${derived}"`
    );
  }
  const key = published ?? derived;
  const dir = join(root, 'src/lib', key);
  const jsonPath = join(dir, `${key}.json`);
  const data = await readSource(lottieLocation(icon.lottie));

  mkdirSync(dir, { recursive: true });
  // Keep existing files untouched when the animation itself hasn't changed (avoids formatting churn).
  if (
    !existsSync(jsonPath) ||
    JSON.stringify(JSON.parse(readFileSync(jsonPath, 'utf8'))) !== JSON.stringify(JSON.parse(data))
  ) {
    writeFileSync(jsonPath, data);
    console.log(`  updated ${key}.json`);
  }
  writeFileSync(
    join(dir, 'index.ts'),
    `import type { Animation } from '../../types';
import animationData from './${key}.json';

const ${key}: Animation = { animationData, animationKey: '${key}' };

export default ${key};
`
  );
  icons.push({ key, interaction: icon.interaction, full: Boolean(icon.requiresFullPlayer) });
}

icons.sort((a, b) => a.key.localeCompare(b.key));

writeFileSync(
  join(root, 'src/icons.ts'),
  `// Generated by scripts/sync-icons.mjs from the useAnimations catalog (icons.json). Do not edit by hand.
import type { Interaction } from './types';

export const interactions = {
${icons.map(({ key, interaction }) => `  ${key}: '${interaction}',`).join('\n')}
} as const satisfies Record<string, Interaction>;

export type AnimationKey = keyof typeof interactions;

// Icons that use features missing from the lottie_light player (e.g. expressions).
export const fullPlayerIcons: ReadonlySet<string> = new Set([${icons
    .filter(({ full }) => full)
    .map(({ key }) => `'${key}'`)
    .join(', ')}]);
`
);

const readmePath = join(root, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const list = icons.map(({ key }) => `\`${key}\``).join(', ');
writeFileSync(
  readmePath,
  readme.replace(/(<!-- icons:start -->)[\s\S]*?(<!-- icons:end -->)/, `$1\n${list}\n$2`)
);

console.log(`Synced ${icons.length} icons.`);
